name: CI

on: [push]

jobs:
   
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i --no-audit --prefer-offline
      - uses: tinovyatkin/action-eslint@v1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          check-name: eslint

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]
        redis-version: [5]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start Redis
      uses: superchargejs/redis-github-action@v1
      with:
        redis-version: ${{ matrix.redis-version }}

    - run: npm i --no-audit --prefer-offline
    - run: npm benchmark
