name: CI

on: [push]

jobs:
   
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
    - name: ESLint Action
      uses: hallee/eslint-action@1.0.1

  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]
        redis-version: [3, 4, 5]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start Redis
      uses: superchargejs/redis-github-action@v1
      with:
        redis-version: ${{ matrix.redis-version }}

    - run: npm install
    - run: npm benchmark
